name: Docker

on:
  workflow_call: 
jobs:

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup Docker Build
      uses: docker/setup-buildx-action@v2.0.0
      
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:

        name: programa

    - name: Docker Login

      uses: docker/login-action@v2.0.0
      with:

        username: mrezende1

        password: ${{ secrets.PASSWORD_DOCKER_HUB }}
        
        
    - name: Build and push Docker images

      uses: docker/build-push-action@v3.1.1
      with:

        context: .

        file: ./Dockerfile

        push: true

        tags: mrezende1/go_ci:${{github.ref_name}}
